# Generated by Django 4.0.4 on 2022-05-04 19:22

from django.db import migrations
import fusion_core.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0003_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=fusion_core.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
