# Generated by Django 4.0.4 on 2022-05-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0004_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trab',
            old_name='trabs',
            new_name='trab',
        ),
    ]
