# Generated by Django 4.0.4 on 2022-05-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0005_rename_trabs_trab_trab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(max_length=250, verbose_name='Bio'),
        ),
    ]
