# Generated by Django 4.0.4 on 2022-05-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0006_alter_funcionario_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('editado', models.DateField(auto_now=True, verbose_name='Editado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('recurso', models.CharField(max_length=100, verbose_name='Trabs')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descriçao')),
                ('icone', models.ImageField(choices=[('lni-laptop-phone', 'Laptop_Phone'), ('lni-cog', 'Engranagem'), ('lni-leaf', 'Planta'), ('lni-layers', 'Quadrado'), ('lni-rocket', 'Foquete')], max_length=16, upload_to='', verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
            },
        ),
    ]
