# Generated by Django 4.0.4 on 2022-05-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0007_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='recurso',
            field=models.CharField(max_length=100, verbose_name='Recurso'),
        ),
    ]
