# Generated by Django 4.0.4 on 2022-05-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0010_recurso_lado_alter_recurso_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='lado',
            field=models.ImageField(choices=[('content-left', 'Lado Esquerdo'), ('content-right', 'Lado Direito')], max_length=13, upload_to='', verbose_name='Lado'),
        ),
    ]
