# Generated by Django 4.0.4 on 2022-05-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0011_alter_recurso_lado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='lado',
        ),
    ]
