# Generated by Django 4.0.4 on 2022-05-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0015_recursoesquerda_rename_recurso_recursodireita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursodireita',
            name='recurso_direita',
            field=models.CharField(max_length=100, verbose_name='Recurso Direita'),
        ),
        migrations.AlterField(
            model_name='recursoesquerda',
            name='recurso_esquerda',
            field=models.CharField(max_length=100, verbose_name='Recurso Esquerda'),
        ),
    ]
