# Generated by Django 4.0.4 on 2022-05-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0016_alter_recursodireita_recurso_direita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursoesquerda',
            options={'verbose_name': 'recurso_esquerda', 'verbose_name_plural': 'recursos_esquerda'},
        ),
    ]
