# Generated by Django 4.0.4 on 2022-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion_core', '0017_alter_recursoesquerda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('editado', models.DateField(auto_now=True, verbose_name='Editado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('nome', models.CharField(max_length=100, verbose_name='Titulo')),
                ('icone', models.ImageField(choices=[('lni-package', 'caixa'), ('lni-drop', 'gota de agua'), ('lni-star', 'estrela')], max_length=11, upload_to='', verbose_name='Icone')),
                ('description_1', models.CharField(max_length=100, verbose_name='Descriçao 1')),
                ('description_2', models.CharField(max_length=100, verbose_name='Descriçao 2')),
                ('description_3', models.CharField(max_length=100, verbose_name='Descriçao 3')),
                ('description_4', models.CharField(max_length=100, verbose_name='Descriçao 4')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
